version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
